[WIN32] fixed: compilation errors. Unsure if include order matters therefore using more ifdef's.
git-svn-id: https://svn.exotica.org.uk:8443/xbmc4xbox@20024 568bbfeb-2a22-0410-94d2-cc84cf5bfa90