[WIN32] fixed compilation error introduced by r17301.
git-svn-id: https://svn.exotica.org.uk:8443/xbmc4xbox@17304 568bbfeb-2a22-0410-94d2-cc84cf5bfa90