merged: upnp from branches/linuxport (16517) fixed: upnp compilation errors due to Unicode support
git-svn-id: https://svn.exotica.org.uk:8443/xbmc4xbox@16520 568bbfeb-2a22-0410-94d2-cc84cf5bfa90