fixed: compilation error due to different return values.
git-svn-id: https://svn.exotica.org.uk:8443/xbmc4xbox@23119 568bbfeb-2a22-0410-94d2-cc84cf5bfa90