merged: xbmc mainline old svn r12473 - fixed: CDirectory::Exists() would always return false. merged: xbmc mainline old svn r12500 - [win32]: fixed CHDDirectory::Exists. Windows needs to test first on INVALID_FILE_ATTRIBUTES. Otherwise it'll return true even when the directory isn't existing. merged: xbmc mainline old svn r12505 - fixed: compilation error and misc. warnings
old bug! This fixes keymap loading failure on WIN32 build due to broken CDirectory::Exists() check.

git-svn-id: https://svn.exotica.org.uk:8443/xbmc4xbox@31789 568bbfeb-2a22-0410-94d2-cc84cf5bfa90